INSERT INTO produto (nome, descricao, valor, tipo) VALUES ('quatro Queijos', 'teste', 50, 'pizza')
INSERT INTO produto (nome, descricao, valor, tipo) VALUES ('quatro Queijos', 'teste', 50, 'pizza')
INSERT INTO produto (nome, descricao, valor, tipo) VALUES ('quatro Queijos', 'teste', 50, 'pizza')
INSERT INTO produto (nome, descricao, valor, tipo) VALUES ('quatro Queijos', 'teste', 50, 'pizza')
INSERT INTO produto (nome, descricao, valor, tipo) VALUES ('quatro Queijos', 'teste', 50, 'pizza')
INSERT INTO produto (nome, descricao, valor, tipo) VALUES ('quatro Queijos', 'teste', 50, 'pizza')
